### ISSUE TITLE
把弹幕变成规范这个提案的目的是什么？

### ISSUE THREAD

**Issue by LongTengDao** [w3c-proposal-incubation/w3c-proposal-incubation.github.io#4]
原生化，以提升性能？
还是只是某种具体实现（或许是最佳实践）的公开文档？

**Comment by flyingzl** [comment]
为什么要有规范？其实我想更多的是为了标准化，为了减轻开发者的负担。比如现在有web，有各种小程序，web上一套弹幕实现，小程序上一种弹幕实现，是否可以考虑统一起来呢？ 

比如以前我们想播放一个视频，需要flash，现在有了html5的 video就方便了很多。为了丰富观看视频体验，亚洲地区有了弹幕，弹幕又可以用css3或者canvas来实现，能否更加简单一点，用一两个标签来实现呢？ 所以中文兴趣组就考虑能否提一个弹幕的规范， 来更加方便快捷的进行web开发。

**Comment by LongTengDao** [comment]
原来如此！这么说可以可以基于理性和实践提issue建议和PR，而不局限于当前项目的参与者基于特定实现优化、旁人只能当看客？又或者现在还没到那么成熟的阶段，虽然意图如此，但是暂时对公众参与并不具备那样的容纳力？谢谢解答

**Comment by xfq** [comment]
Moved to https://github.com/w3c/danmaku/issues/9
